### ISSUE TITLE
确认master里自动远征已屏蔽

### ISSUE THREAD

**Issue by traburiss** [Zjsn-develop/ZjsnViewer#18]
我把昨天不小心同步到master里面的自动远征屏蔽了，然而感觉不靠谱，请帮忙确认是否已屏蔽。

**Comment by JohnnySun** [comment]
分支有点乱了。。。我去看看

**Comment by JohnnySun** [comment]
好像是没有。。。

**Comment by PaleNeutron** [comment]
并没有，我今天还用master版本自动远征来着。
不过操作过快的那个确实被修复了

**Comment by traburiss** [comment]
我这里测试了一下，自动远征貌似已经没有了，我push了代码到master了，各位可以测一下。
