### ISSUE TITLE
完善wiki里的API列表

### ISSUE THREAD

**Issue by JohnnySun** [Zjsn-develop/ZjsnViewer#2]

**Comment by JohnnySun** [comment]
我明天抽空吧手里现有的这些api整理下

**Comment by PaleNeutron** [comment]
我稍微整理了下格式，不过有更多的API吗？最好每个API再弄个详细的response说明

**Comment by JohnnySun** [comment]
@PaleNeutron api我这几乎全有，今天有点太晚了，我明天整理下发出来，response那个慢慢来，回头慢慢弄出来

**Comment by JohnnySun** [comment]
基本api补充完成
