### ISSUE TITLE
exp分支里的自动远征功能

### ISSUE THREAD

**Issue by JohnnySun** [Zjsn-develop/ZjsnViewer#3]
之前为了测试省事，exp分支里的分时间自动远征的时间设置走的是通知设置里的免打扰时段，经过这几天的测试并没有什么问题，准备把自动远征的时间设置和自动远征开关单独放到一个隐藏的菜单中。 是否这些有争议的功能都应该隐藏，有待讨论

**Comment by traburiss** [comment]
自动远征是指远征结束后自动继续重复之前远征吗？
说实话这个功能最好谨慎，你萌知道肯定会禁的，我是不敢用。建议测试的话最好不要拿主号来测试，如果是秒续远征的话后台数据一抓是很容易找出来的。

**Comment by JohnnySun** [comment]
这玩意安全性有待考证，但是秒续也不可能拉，毕竟这辅助后台登录一次也要几分钟，而且现在暂时加了一个停止时间段，感觉来说，还是有很多要改进的地方

**Comment by JohnnySun** [comment]
回头加个开关单独弄出来吧，默认特性肯定是不好的

**Comment by PaleNeutron** [comment]
秒续问题不用担心，现在的续远征的效率还不如按键精灵呢。我担心的是request的特征和客户端心跳之类的问题。毕竟咱们发的request虽然能被服务器接受和返回，但是和真实客户端发出的有不少差距。如果要做自动远征那就必须在这方面做到一致，不然根本不用行为分析，直接看request就能准确的抓出来，风险太大。

**Comment by JohnnySun** [comment]
这边我昨天已经加上了时间戳和校验戳，现在服务器返回的数据已经直接是gzip压缩的了，那既然这样，这几天加上&gz=1好了，这样的话，就没有什么问题了

**Comment by PaleNeutron** [comment]
`选择地图 	/pve/cha11enge/地图编号/舰队ID/0[暂时意义不明]/`
后面这个意义不明的东西有思路了吗？这个搞定了就可以用viewer炸鱼了……（死

**Comment by JohnnySun** [comment]
那个你不用管，后面接0就行，我只是不知道那个0是啥

**Comment by JohnnySun** [comment]
用viewer炸鱼的话还需要先做好自动判断大破，自动修船

**Comment by traburiss** [comment]
喂喂喂~~越来越朝着外挂的方向去了啊~~~我可不想辛辛苦苦搞出来的东西被你萌封掉啊~~~~

**Comment by JohnnySun** [comment]
@traburiss 啊啊啊啊,好像真的欸,这些功能弄个隐藏的activity放起来吧,当成一个彩蛋好啦....

**Comment by JohnnySun** [comment]
功能基本完成 #closed

**Comment by PaleNeutron** [comment]
非stable的版本最好再experiment分支开发，开发一段时间之后再统一merge到master分支上

在 2016-06-17 10:53:50，"LTC" <notifications@github.com> 写道：


Closed #3.
